# Generated by Django 4.2.10 on 2024-03-01 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domo_api', '0004_rename_dattime_dots_dattime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dots',
            old_name='device_id',
            new_name='device',
        ),
    ]
